### ISSUE TITLE
Doublestrike 1080i Mode

### ISSUE THREAD

**Issue by WNKLER** [chriz2600/time-sleuth#2]
Is it possible to add a doublestrike 1080i mode?
Would it be as simple as changing the v_*_2 settings as shown in the image below?

The best comparison I can think of is how 240p is just doubletriked 480i.

This would be for evaluating 33.75 kHz displays in progressive mode.

![540p](https://user-images.githubusercontent.com/29347893/96028818-cf568780-0e27-11eb-8add-a34592b65db9.gif)

**Comment by roostercactus** [comment]
Hi, yes 540p would be nice.  The MiSTer can output 540p to a Sony HD CRT and this would be great to verify the lag at this resolution.  Thanks!

**Comment by chriz2600** [comment]
Ok! I think I can add it to the custom firmware generator [(time-sleuth.i74.de/)](https://time-sleuth.i74.de/)
Give me a couple of days and I will add it!

**Comment by chriz2600** [comment]
540p is now available on the custom firmware generator: [time-sleuth.i74.de](https://time-sleuth.i74.de/)

**Comment by roostercactus** [comment]
@Finatra Hi, I was wondering where that table with the timing values came from?  Can you please share the title of the document you found it in?  Thanks!

**Comment by WNKLER** [comment]
I made the table myself.

The values came from //source/config/video_modes.v in this ghit.

I put only the values shown into a table just to clearly illustrate my request.
