### ISSUE TITLE
Add additional modes (1280x768@60 1360x768@60)

### ISSUE THREAD

**Issue by Grinkers** [chriz2600/time-sleuth#4]
Is it possible to add modes for 1280x768@60 1360x768@60?

Both of these resolutions are commonly used in many Japanese arcade cabinets.

**Comment by chriz2600** [comment]
Yes, that's possible, but I need to know the exact video timings for these modes. Are those one of the modes described by VESA [VESA-DMT-1.13.pdf](https://glenwing.github.io/docs/VESA-DMT-1.13.pdf)?

**Comment by Grinkers** [comment]
Thank you very much for responding.

The arcade cabinets essentially just industrial use monitors. I don't know explicitly about conforming to the VESA standards, but these displays work with standard PC's, consoles, etc. If anything further needs to be investigated I can get it (edid info etc. although physical investigation is quite labor intensive).
